#!python
# emacs: -*- mode: python-mode; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:
"""
Check and process solution notebook to generate exercise notebook.
"""

from rnbgrader.nbprocessor import run_process


if __name__ == '__main__':
    run_process()
